---
- hosts: 172.31.20.64
  become: yes
  tasks:
  - name: i want to create folder
    file: 
      path: /home/maha/myfolder
      state: directory

  - include_tasks: myfile.yml
  
  - name: copy the file into node side
    copy: 
      src: mytestfile
      dest: /home/maha/myfolder
