---
- hosts: 172.31.20.64
  become: yes
  tasks:
  - name: i want to create folder
    file: 
      path: /home/maha/myfolder
      state: directory

  - include_tasks: myfile.yml

  - name: copy the file into node side
    copy: 
      src: mytestfile.yml
      dest: /home/maha/myfolder

  - name: i want to download internet file
    get_url:
         url: https://downloads.apache.org/tomcat/tomcat-10/v10.1.23/bin/apache-tomcat-10.1.23-windows-x86.zip
         dest: /home/maha/myfolder/apache-tomcat-10.1.23-windows-x86.zip
         force_basic_auth: yes