---
- hosts: 172.31.20.64
  become: yes
  tasks:
  - name: i want to create folder
    file: 
      path: /home/maha/myfolder
      state: directory

  - name: i want to create a file 
    file: 
      path: /home/maha/myfolder/myfirstfile
      state: touch
